insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('820', 'guitar, bass', '500', '700');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('821', 'synth, piano', '500', '701');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('822', 'guitar', '800', '702');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('823', 'saxophone', '900', '703');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('824', 'maracas, bass', '200', '704');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('825', 'guitar, bass, maracas, saxophone', '600', '705');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('826', 'microphone, bass', '755', '706');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('827', 'guitar, synth', '600', '707');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('828', 'piano, bass', '900', '708');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('829', 'piano', '300', '709');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('830', 'guitar, bass, piano, synth', '600', '710');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('831', 'guitar', '400', '711');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('832', 'microphone', '900', '712');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('833', 'guitar, bass', '200', '713');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('834', 'synth, piano', '700', '714');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('835', 'drums, bass', '600', '715');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('836', 'accordion, bass', '300', '716');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('837', 'trumpet, flute', '500', '717');
insert into instructor (instructor_id, instructor_arsenal, instructor_price, person_id) values ('838', 'trumpet, flute', '600', '718');